### ISSUE TITLE
Cannot get 1.0.2 from https://invesdwin.de/repo/invesdwin-oss-remote/

### ISSUE THREAD

**Issue by paulvi** [invesdwin/invesdwin-context-python#1]
I try to use in Maven

```xml
    <dependencies>

        <!-- https://github.com/invesdwin/invesdwin-context-python -->
        <dependency>
            <groupId>de.invesdwin</groupId>
            <artifactId>invesdwin-context-python-runtime-jep</artifactId>
            <version>1.0.2</version><!---project.version.invesdwin-context-python-parent-->
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>invesdwin-de-repo</id>
            <url>https://invesdwin.de/repo/invesdwin-oss-remote/</url>
        </repository>
    </repositories>
```

and I get 

> [ERROR] Failed to execute goal on project hedging-strategy-python: Could not resolve dependencies for project com.huobi.pool:hedging-strategy-python:jar:0.0.1-SNAPSHOT: Failure to find de.invesdwin:invesdwin-context-python-runtime-jep:jar:1.0.2 in https://invesdwin.de/repo/invesdwin-oss-remote/ was cached in the local repository, resolution will not be reattempted until the update interval of invesdwin-de-repo has elapsed or updates are forced -> [Help 1]

looking into nexus, I see no `de.*` packages at all at top

https://invesdwin.de/nexus/#browse/browse:invesdwin-oss-remote

![image](https://user-images.githubusercontent.com/1614482/120998428-ab7ef200-c7ba-11eb-91ef-2757ba000619.png)

or only 1.0.3 SNAPSHOTs, 

![image](https://user-images.githubusercontent.com/1614482/120998520-bf2a5880-c7ba-11eb-8a59-dfaa71b5328d.png)

**Comment by subes** [comment]
de is on the bottom:
![grafik](https://user-images.githubusercontent.com/332937/121004333-d8b5ab00-c78e-11eb-8ee7-811d74c2f0e0.png)

**Comment by subes** [comment]
I have also reuploaded the artifacts directly to nexus3. The proxy to the old artifactory instance did now work because artifactory was down. I have started it up again. Notify me if any other artifacts are missing as well. Then I will reupload then as well.

Though you should be able to try again now and this specific artifact should resolve fine.
