### ISSUE TITLE
Please consider to release OSS part into maven central

### ISSUE THREAD

**Issue by paulvi** [invesdwin/invesdwin-context-python#2]
Please consider to release OSS part into maven central (maybe via Sonatype OSS )

Consuming 3rd parties repositories is not convenient, when company already has own Nexus (It required talk with admin)

And it should be more trust for packages fully public, not on self hosted server.

**Comment by subes** [comment]
Currently the additional work to publish to maven central is not in scope (with the hundreds of artifacts we have). Also we like to stay in control over where these artifacts are sourced officially from. See also discussions and related requests here: https://github.com/invesdwin/invesdwin-instrument/issues/17#issuecomment-728772422
