### ISSUE TITLE
How to use this and its limitations

### ISSUE THREAD

**Issue by Cyberavater** [invesdwin/invesdwin-context-python#6]
I've landed here from [here](https://stackoverflow.com/a/44472897/13519865).

1.
Now if I understand correctly using `invesdwin-context-python-runtime-python4j` I can easily use Python packages on JVM (even where there is no Python installed). Other options require Python installed on the host machine right?

2. 
It seems I can't add it to my project, can you help me?

``
:simpleTests:main: Could not find de.invesdwin:invesdwin-context-python-runtime-python4j:1.0.3.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/de/invesdwin/invesdwin-context-python-runtime-python4j/1.0.3/invesdwin-context-python-runtime-python4j-1.0.3.pom
  - https://repo.maven.apache.org/maven2/de/invesdwin/invesdwin-context-python-runtime-python4j/1.0.3/invesdwin-context-python-runtime-python4j-1.0.3.pom
  - https://jitpack.io/de/invesdwin/invesdwin-context-python-runtime-python4j/1.0.3/invesdwin-context-python-runtime-python4j-1.0.3.pom
  - https://invesdwin.de/repo/invesdwin-oss-remote/de/invesdwin/invesdwin-context-python-runtime-python4j/1.0.3/invesdwin-context-python-runtime-python4j-1.0.3.pom
Required by:
    project :simpleTests

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

``

**Comment by subes** [comment]
1. yes
2. https://github.com/invesdwin/invesdwin-context-python/issues/5 (you should use a newer version of python4j and add python packages as need)
3. you might want to look at jep or py4j for calling java from python and using https://stackoverflow.com/questions/35842/how-can-a-java-program-get-its-own-process-id (i am also working on a simplified callJava abstraction to make that availabe in the other bindings as well) or if you want to call python from java, look at the example testcases provided in the project by using the AScriptTaskPython abstraction.

**Comment by Cyberavater** [comment]
But how will I install `psutil` in embedded python interpreter?

**Comment by subes** [comment]
Please ask nd4j developers, I guess they only provide prebuilt embeddable packages for numpy: 
![grafik](https://github.com/invesdwin/invesdwin-context-python/assets/332937/88b4923e-d2eb-40bb-a28c-1045bc93333c)

**Comment by subes** [comment]
It seems they support bundling up a miniconda installation (on same python version) as a zip file and giving that as a system property to python4j to be able to include external python dependencies: https://deeplearning4j.konduit.ai/python4j/reference/python-path
